import { CalculatorDefinition, CalcField } from "../lib/types";
import {
  calculateLength, calculateWeight, calculateArea, calculateVolume, calculateSpeed,
  calculateTime, calculateDataStorage, calculateEnergy, calculatePressure, calculatePower,
  calculateTemperature,
} from "../lib/calculations/conversions";
import {
  LENGTH, WEIGHT, AREA, VOLUME, SPEED, TIME, DATA_STORAGE, ENERGY, PRESSURE, POWER,
  TEMPERATURE_UNITS, UnitCategory,
} from "../lib/units/tables";

function unitFields(category: UnitCategory, defaultFrom: string, defaultTo: string): CalcField[] {
  const options = category.units.map((u) => ({ label: u.label, value: u.id }));
  return [
    { id: "value", label: "Value", type: "number", defaultValue: "1", required: true },
    { id: "from", label: "From", type: "select", defaultValue: defaultFrom, options },
    { id: "to", label: "To", type: "select", defaultValue: defaultTo, options },
  ];
}

export const conversionCalculators: CalculatorDefinition[] = [
  {
    slug: "length-converter",
    title: "Length Converter",
    category: "conversions",
    description: "Convert between metric, imperial, nautical, and astronomical length units.",
    fields: unitFields(LENGTH, "km", "mi"),
    calculate: calculateLength,
    formula: "Result = (Value × FromUnit→meter) ÷ ToUnit→meter",
    explanation: "Every length unit converts through a common base — the meter. The value is first converted to meters, then from meters into the target unit.",
    example: { inputs: { value: "10", from: "km", to: "mi" }, note: "10 km ≈ 6.21 miles" },
    faq: [
      { q: "How precise are these conversions?", a: "Conversion factors use internationally defined exact values (e.g. 1 inch = 0.0254 m exactly) where such standards exist." },
      { q: "Can I see multiple unit equivalents at once?", a: "Use the Universal Unit Converter for a multi-unit breakdown of a single value." },
    ],
    related: ["weight-converter", "speed-converter", "area-converter"],
  },
  {
    slug: "weight-converter",
    title: "Weight / Mass Converter",
    category: "conversions",
    description: "Convert between metric and imperial weight/mass units.",
    fields: unitFields(WEIGHT, "kg", "lb"),
    calculate: calculateWeight,
    formula: "Result = (Value × FromUnit→kg) ÷ ToUnit→kg",
    explanation: "Weight/mass units all convert through kilograms as the common base unit, using standardized exact conversion factors.",
    example: { inputs: { value: "100", from: "kg", to: "lb" }, note: "100 kg ≈ 220.46 lb" },
    faq: [
      { q: "Is weight the same as mass?", a: "Colloquially yes, and this converter treats them the same way common unit converters do — as mass units." },
      { q: "What's the difference between a US ton and a UK ton?", a: "A US short ton is 2,000 lb (907.18 kg); a UK long ton is 2,240 lb (1,016.05 kg) — both are included as separate units." },
    ],
    related: ["length-converter", "volume-converter"],
  },
  {
    slug: "temperature-converter",
    title: "Temperature Converter",
    category: "conversions",
    description: "Convert between Celsius, Fahrenheit, Kelvin, and less common historical scales.",
    fields: [
      { id: "value", label: "Value", type: "number", defaultValue: "72", required: true },
      { id: "from", label: "From", type: "select", defaultValue: "fahrenheit", options: TEMPERATURE_UNITS.map((u) => ({ label: u.label, value: u.id })) },
      { id: "to", label: "To", type: "select", defaultValue: "celsius", options: TEMPERATURE_UNITS.map((u) => ({ label: u.label, value: u.id })) },
    ],
    calculate: calculateTemperature,
    formula: "Convert to Celsius, then from Celsius to the target scale (each scale has its own offset formula)",
    explanation: "Unlike most units, temperature scales aren't simple multiples of each other — they have different zero points. Every conversion routes through Celsius as an intermediate step.",
    example: { inputs: { value: "72", from: "fahrenheit", to: "celsius" }, note: "72°F ≈ 22.2°C" },
    faq: [
      { q: "Why can't Kelvin be negative?", a: "Kelvin measures from absolute zero, the coldest physically possible temperature, so negative Kelvin values don't exist." },
      { q: "What is the Rømer or Newton scale?", a: "These are historical temperature scales rarely used today, included here for completeness and reference." },
    ],
    related: ["length-converter", "pressure-converter"],
  },
  {
    slug: "area-converter",
    title: "Area Converter",
    category: "conversions",
    description: "Convert between square-meter, square-foot, acre, hectare, and other area units.",
    fields: unitFields(AREA, "acre", "m2"),
    calculate: calculateArea,
    formula: "Result = (Value × FromUnit→m²) ÷ ToUnit→m²",
    explanation: "Area units convert through square meters as the common base, using the square of each unit's linear conversion factor.",
    example: { inputs: { value: "1", from: "acre", to: "m2" }, note: "1 acre ≈ 4046.86 m²" },
    faq: [
      { q: "How big is a hectare?", a: "A hectare is exactly 10,000 square meters, roughly 2.47 acres." },
      { q: "What's the difference between an acre and a square mile?", a: "There are 640 acres in one square mile." },
    ],
    related: ["length-converter", "volume-converter"],
  },
  {
    slug: "volume-converter",
    title: "Volume Converter",
    category: "conversions",
    description: "Convert between metric volume, US customary, imperial, and cooking measurements.",
    fields: unitFields(VOLUME, "galUS", "l"),
    calculate: calculateVolume,
    formula: "Result = (Value × FromUnit→liter) ÷ ToUnit→liter",
    explanation: "Volume units convert through liters as the common base. US customary units (cups, gallons) differ from imperial units of the same name, so each is listed separately.",
    example: { inputs: { value: "1", from: "galUS", to: "l" }, note: "1 US gallon ≈ 3.79 liters" },
    faq: [
      { q: "Is a US gallon the same as a UK gallon?", a: "No — a US gallon (3.785 L) is smaller than an imperial gallon (4.546 L)." },
      { q: "Where are cooking units like teaspoons?", a: "Teaspoons, tablespoons, and cups are included, matching US customary definitions." },
    ],
    related: ["cooking-measurement-converter", "area-converter"],
  },
  {
    slug: "speed-converter",
    title: "Speed Converter",
    category: "conversions",
    description: "Convert between km/h, mph, knots, m/s, and Mach.",
    fields: unitFields(SPEED, "kmh", "mph"),
    calculate: calculateSpeed,
    formula: "Result = (Value × FromUnit→m/s) ÷ ToUnit→m/s",
    explanation: "Speed units convert through meters per second as the base. Mach is approximated at sea-level standard conditions and varies with altitude and temperature in reality.",
    example: { inputs: { value: "36", from: "kmh", to: "mps" }, note: "36 km/h = 10 m/s" },
    faq: [
      { q: "Is a knot the same as mph?", a: "No — 1 knot (nautical mile per hour) ≈ 1.15 mph." },
      { q: "Is the Mach conversion exact?", a: "It's an approximation at sea level; the speed of sound changes with air temperature and altitude." },
    ],
    related: ["length-converter", "time-converter"],
  },
  {
    slug: "time-converter",
    title: "Time Converter",
    category: "conversions",
    description: "Convert between seconds, minutes, hours, days, weeks, months, and years.",
    fields: unitFields(TIME, "hr", "min"),
    calculate: calculateTime,
    formula: "Result = (Value × FromUnit→second) ÷ ToUnit→second",
    explanation: "Time units convert through seconds as the base unit. Months and years use average calendar lengths (30.44 and 365.25 days respectively) since they aren't fixed durations.",
    example: { inputs: { value: "2", from: "hr", to: "min" }, note: "2 hours = 120 minutes" },
    faq: [
      { q: "Why is a month 30.44 days here?", a: "Calendar months vary from 28–31 days, so the converter uses the average length across a year (365.25 ÷ 12)." },
      { q: "Does this account for leap years?", a: "The year unit uses 365.25 days, which already averages in the leap-year extra day." },
    ],
    related: ["unix-timestamp-converter", "date-calculator"],
  },
  {
    slug: "data-storage-converter",
    title: "Data Storage Converter",
    category: "conversions",
    description: "Convert between decimal (KB, MB, GB) and binary (KiB, MiB, GiB) data storage units.",
    fields: unitFields(DATA_STORAGE, "gb", "gib"),
    calculate: calculateDataStorage,
    formula: "Result = (Value × FromUnit→byte) ÷ ToUnit→byte",
    explanation: "Storage capacity is measured in two competing systems: decimal (powers of 1000, as used in marketing and hard drive sizes) and binary (powers of 1024, as used by most operating systems for memory).",
    example: { inputs: { value: "1", from: "gb", to: "gib" }, note: "1 GB ≈ 0.9313 GiB — they are NOT the same size." },
    faq: [
      { q: "Why does my hard drive show less space than advertised?", a: "Manufacturers label capacity in decimal GB, but operating systems often display binary GiB, which requires more bytes per unit — creating an apparent 'missing' amount of space." },
      { q: "Which should I use for RAM?", a: "RAM capacity is conventionally binary (GiB), even though it's often labeled 'GB'." },
    ],
    related: ["byte-size-converter", "base-converter"],
  },
  {
    slug: "energy-converter",
    title: "Energy Converter",
    category: "conversions",
    description: "Convert between joules, calories, watt-hours, BTU, and other energy units.",
    fields: unitFields(ENERGY, "kcal", "kj"),
    calculate: calculateEnergy,
    formula: "Result = (Value × FromUnit→joule) ÷ ToUnit→joule",
    explanation: "Energy units convert through the joule, the SI base unit of energy, whether the source is mechanical work, heat, or electrical energy.",
    example: { inputs: { value: "1", from: "kcal", to: "kj" }, note: "1 kcal ≈ 4.184 kJ" },
    faq: [
      { q: "What's the difference between a calorie and a Calorie (kcal)?", a: "Food labels use 'Calorie' (capital C) to mean kilocalorie — 1,000 small calories." },
      { q: "What is an electronvolt used for?", a: "It's a tiny unit of energy used in atomic and particle physics." },
    ],
    related: ["power-converter", "pressure-converter"],
  },
  {
    slug: "pressure-converter",
    title: "Pressure Converter",
    category: "conversions",
    description: "Convert between pascal, bar, atmosphere, PSI, torr, and mmHg.",
    fields: unitFields(PRESSURE, "psi", "kpa"),
    calculate: calculatePressure,
    formula: "Result = (Value × FromUnit→pascal) ÷ ToUnit→pascal",
    explanation: "Pressure units convert through the pascal (Pa), the SI base unit, which represents one newton of force per square meter.",
    example: { inputs: { value: "1", from: "atm", to: "pa" }, note: "1 atmosphere = 101,325 Pa" },
    faq: [
      { q: "What's normal tire pressure in kPa if I know PSI?", a: "Multiply PSI by roughly 6.895 to get kPa, or use this converter directly." },
      { q: "What is torr used for?", a: "Torr is commonly used in vacuum and laboratory pressure measurements; 1 torr ≈ 1 mmHg." },
    ],
    related: ["energy-converter", "power-converter"],
  },
  {
    slug: "power-converter",
    title: "Power Converter",
    category: "conversions",
    description: "Convert between watts, kilowatts, horsepower, and BTU/hour.",
    fields: unitFields(POWER, "hp", "kw"),
    calculate: calculatePower,
    formula: "Result = (Value × FromUnit→watt) ÷ ToUnit→watt",
    explanation: "Power measures the rate of energy transfer. All units here convert through the watt, the SI base unit, equal to one joule per second.",
    example: { inputs: { value: "1", from: "hp", to: "kw" }, note: "1 mechanical horsepower ≈ 0.746 kW" },
    faq: [
      { q: "Is metric horsepower the same as mechanical horsepower?", a: "No — metric horsepower (PS) is slightly smaller (735.5 W) than mechanical horsepower (745.7 W)." },
      { q: "What is a 'ton of refrigeration'?", a: "It's a power unit used in HVAC, equal to the cooling effect of melting one short ton of ice in 24 hours — not included by default but can be added to the registry." },
    ],
    related: ["energy-converter", "electricity-cost-calculator"],
  },
];
