import { CalculatorDefinition } from "../lib/types";
import {
  calculateSimpleInterest, calculateCompoundInterest, calculateEMI, calculateMortgage,
  calculateSIP, calculateROI, calculateProfitLoss, calculateDiscount, calculateTax,
  calculateSalary, calculateCurrency, calculateInflation, calculateTip,
  STATIC_FX_RATES_USD,
} from "../lib/calculations/finance";

const currencyOptions = Object.keys(STATIC_FX_RATES_USD).map((c) => ({ label: c, value: c }));

export const financeCalculators: CalculatorDefinition[] = [
  {
    slug: "simple-interest-calculator",
    title: "Simple Interest Calculator",
    category: "finance",
    description: "Calculate simple interest and total payable on a loan or deposit.",
    fields: [
      { id: "principal", label: "Principal", type: "number", defaultValue: "1000", required: true },
      { id: "rate", label: "Annual interest rate (%)", type: "number", defaultValue: "5", required: true },
      { id: "time", label: "Time (years)", type: "number", defaultValue: "2", required: true },
    ],
    calculate: calculateSimpleInterest,
    formula: "SI = (P × R × T) ÷ 100",
    explanation: "Simple interest grows linearly: the same amount of interest accrues every period because it's always calculated on the original principal, never on previously earned interest.",
    example: { inputs: { principal: "1000", rate: "5", time: "2" }, note: "Interest = ₹100 on a ₹1000 principal over 2 years at 5%." },
    faq: [
      { q: "How is simple interest different from compound interest?", a: "Simple interest is always calculated on the original principal; compound interest is calculated on principal plus previously accumulated interest." },
      { q: "Can I use this for savings deposits?", a: "Yes, the same formula works whether you're borrowing or saving." },
    ],
    related: ["compound-interest-calculator", "loan-emi-calculator"],
  },
  {
    slug: "compound-interest-calculator",
    title: "Compound Interest Calculator",
    category: "finance",
    description: "Calculate compound interest with any compounding frequency (annual, monthly, daily, etc.).",
    fields: [
      { id: "principal", label: "Principal", type: "number", defaultValue: "1000", required: true },
      { id: "rate", label: "Annual interest rate (%)", type: "number", defaultValue: "10", required: true },
      { id: "time", label: "Time (years)", type: "number", defaultValue: "5", required: true },
      { id: "compoundsPerYear", label: "Compounds per year", type: "select", defaultValue: "1", options: [
        { label: "Annually (1)", value: "1" }, { label: "Semi-annually (2)", value: "2" },
        { label: "Quarterly (4)", value: "4" }, { label: "Monthly (12)", value: "12" }, { label: "Daily (365)", value: "365" },
      ] },
    ],
    calculate: calculateCompoundInterest,
    formula: "A = P × (1 + r/(100n))^(n×t)",
    explanation: "Compound interest earns 'interest on interest': each compounding period's interest is added to the principal before the next period's interest is calculated, so growth accelerates over time.",
    example: { inputs: { principal: "1000", rate: "10", time: "5", compoundsPerYear: "1" }, note: "₹1000 at 10% annually for 5 years grows to about ₹1610.51." },
    faq: [
      { q: "Does more frequent compounding always earn more?", a: "Yes — for the same nominal rate, more frequent compounding (e.g. monthly vs. annually) produces a slightly higher effective return." },
      { q: "What if the rate is 0%?", a: "With a 0% rate the amount never grows, so interest earned is zero." },
    ],
    related: ["simple-interest-calculator", "sip-calculator", "inflation-calculator"],
  },
  {
    slug: "loan-emi-calculator",
    title: "Loan / EMI Calculator",
    category: "finance",
    description: "Calculate the monthly installment (EMI) for a loan, plus total interest paid.",
    fields: [
      { id: "principal", label: "Loan amount", type: "number", defaultValue: "1000000", required: true },
      { id: "rate", label: "Annual interest rate (%)", type: "number", defaultValue: "8.5", required: true },
      { id: "years", label: "Loan term (years)", type: "number", defaultValue: "20", required: true },
    ],
    calculate: calculateEMI,
    formula: "EMI = P × r × (1+r)^n ÷ ((1+r)^n − 1)",
    explanation: "The Equated Monthly Installment (EMI) is the fixed amount you repay each month, combining shrinking interest and growing principal portions, so that the loan is fully paid off after n months.",
    example: { inputs: { principal: "1000000", rate: "8.5", years: "20" }, note: "A ₹10,00,000 loan at 8.5% for 20 years has an EMI of about ₹8,678." },
    faq: [
      { q: "Why is early interest higher than later interest?", a: "Interest is charged on the outstanding balance, which is largest at the start of the loan, so more of each early EMI goes to interest." },
      { q: "What happens with a 0% interest rate?", a: "The EMI becomes simply the principal divided by the number of months." },
    ],
    related: ["mortgage-calculator", "compound-interest-calculator"],
  },
  {
    slug: "mortgage-calculator",
    title: "Mortgage Calculator",
    category: "finance",
    description: "Calculate a full monthly mortgage payment including principal, interest, taxes, and insurance.",
    fields: [
      { id: "principal", label: "Loan amount", type: "number", defaultValue: "300000", required: true },
      { id: "rate", label: "Annual interest rate (%)", type: "number", defaultValue: "6.5", required: true },
      { id: "years", label: "Loan term (years)", type: "number", defaultValue: "30", required: true },
      { id: "monthlyTax", label: "Monthly property tax (optional)", type: "number", defaultValue: "0" },
      { id: "monthlyInsurance", label: "Monthly insurance (optional)", type: "number", defaultValue: "0" },
    ],
    calculate: calculateMortgage,
    formula: "Monthly payment = EMI(principal, rate, term) + monthly tax + monthly insurance",
    explanation: "A mortgage payment usually includes more than principal and interest — property taxes and homeowners insurance, when escrowed, are added to the base loan payment to get the total monthly cost.",
    example: { inputs: { principal: "300000", rate: "6.5", years: "30", monthlyTax: "250", monthlyInsurance: "100" }, note: "Base P&I plus $350/month in tax and insurance." },
    faq: [
      { q: "Does this include PMI (mortgage insurance)?", a: "PMI can be entered under 'Monthly insurance' if it applies to your loan." },
      { q: "How does the term length affect the payment?", a: "Longer terms lower the monthly payment but increase total interest paid over the life of the loan." },
    ],
    related: ["loan-emi-calculator", "compound-interest-calculator"],
  },
  {
    slug: "sip-investment-calculator",
    title: "Investment / SIP Calculator",
    category: "finance",
    description: "Project the future value of regular monthly investments (a Systematic Investment Plan).",
    fields: [
      { id: "monthlyInvestment", label: "Monthly investment", type: "number", defaultValue: "5000", required: true },
      { id: "annualReturnRate", label: "Expected annual return (%)", type: "number", defaultValue: "12", required: true },
      { id: "years", label: "Investment duration (years)", type: "number", defaultValue: "10", required: true },
    ],
    calculate: calculateSIP,
    formula: "FV = P × (((1+r)^n − 1) ÷ r) × (1+r)",
    explanation: "A SIP invests a fixed amount every month. Because each contribution has a different amount of time to grow, the future value formula sums a geometric series of compounding contributions.",
    example: { inputs: { monthlyInvestment: "5000", annualReturnRate: "12", years: "10" }, note: "₹5,000/month at 12% for 10 years grows to roughly ₹11.6 lakh." },
    faq: [
      { q: "Is the return rate guaranteed?", a: "No — this projects a hypothetical constant return; actual market returns vary." },
      { q: "What's the difference between invested amount and future value?", a: "Invested amount is simply monthly investment × months; future value also includes compounding growth on top of that." },
    ],
    related: ["compound-interest-calculator", "roi-calculator"],
  },
  {
    slug: "roi-calculator",
    title: "ROI Calculator",
    category: "finance",
    description: "Calculate return on investment as a percentage gain or loss.",
    fields: [
      { id: "cost", label: "Initial cost / investment", type: "number", defaultValue: "1000", required: true },
      { id: "revenue", label: "Final value / return", type: "number", defaultValue: "1500", required: true },
    ],
    calculate: calculateROI,
    formula: "ROI = ((Final Value − Cost) ÷ Cost) × 100",
    explanation: "Return on investment measures how much value an investment gained or lost, expressed as a percentage of the amount originally put in.",
    example: { inputs: { cost: "1000", revenue: "1500" }, note: "A $1,000 investment that becomes $1,500 has a 50% ROI." },
    faq: [
      { q: "Can ROI be negative?", a: "Yes — a negative ROI means the final value was less than the initial cost." },
      { q: "Does ROI account for the time period?", a: "No, this simple ROI formula ignores time. Use CAGR for annualized returns over multiple years." },
    ],
    related: ["sip-investment-calculator", "profit-loss-calculator"],
  },
  {
    slug: "profit-loss-calculator",
    title: "Profit & Loss Calculator",
    category: "finance",
    description: "Determine whether a sale resulted in profit or loss, and by how much.",
    fields: [
      { id: "costPrice", label: "Cost price", type: "number", defaultValue: "100", required: true },
      { id: "sellingPrice", label: "Selling price", type: "number", defaultValue: "150", required: true },
    ],
    calculate: calculateProfitLoss,
    formula: "Profit/Loss = Selling Price − Cost Price",
    explanation: "Comparing selling price against cost price reveals whether a transaction was profitable, and the percentage figure expresses that profit or loss relative to what was originally spent.",
    example: { inputs: { costPrice: "100", sellingPrice: "150" }, note: "Selling at $150 after paying $100 is a $50 profit (50%)." },
    faq: [
      { q: "What if cost price equals selling price?", a: "The result is neither a profit nor a loss — the difference is zero." },
      { q: "Is the percentage based on cost or selling price?", a: "It's based on the cost price, which is the standard convention for profit/loss percentage." },
    ],
    related: ["discount-calculator", "roi-calculator"],
  },
  {
    slug: "discount-calculator",
    title: "Discount Calculator",
    category: "finance",
    description: "Calculate the final price after applying a percentage discount.",
    fields: [
      { id: "price", label: "Original price", type: "number", defaultValue: "200", required: true },
      { id: "discountPercent", label: "Discount (%)", type: "number", defaultValue: "25", required: true },
    ],
    calculate: calculateDiscount,
    formula: "Final Price = Original Price − (Original Price × Discount% ÷ 100)",
    explanation: "A percentage discount reduces the original price by a proportional amount. This calculator shows the discount amount and the resulting final price.",
    example: { inputs: { price: "200", discountPercent: "25" }, note: "A 25% discount on $200 brings the price to $150." },
    faq: [
      { q: "Can I stack multiple discounts?", a: "Run the calculator once per discount, using the previous result as the new original price." },
      { q: "What if the discount is over 100%?", a: "The calculator will still compute the math, but a discount over 100% produces a negative price, which isn't realistic for most sales." },
    ],
    related: ["percentage-calculator", "tax-calculator"],
  },
  {
    slug: "tax-calculator",
    title: "Tax Calculator",
    category: "finance",
    description: "Add tax to a price, or work backward from a tax-inclusive total to find the base price.",
    fields: [
      { id: "amount", label: "Amount", type: "number", defaultValue: "100", required: true },
      { id: "taxRate", label: "Tax rate (%)", type: "number", defaultValue: "10", required: true },
      { id: "mode", label: "Amount type", type: "select", defaultValue: "exclusive", options: [
        { label: "Amount excludes tax (add tax)", value: "exclusive" },
        { label: "Amount includes tax (back out base price)", value: "inclusive" },
      ] },
    ],
    calculate: calculateTax,
    formula: "Exclusive: Total = Amount × (1 + Rate/100)     |     Inclusive: Base = Total ÷ (1 + Rate/100)",
    explanation: "Tax calculations run in two directions: adding tax onto a pre-tax price, or extracting the pre-tax base price from a total that already includes tax.",
    example: { inputs: { amount: "100", taxRate: "10", mode: "exclusive" }, note: "$100 plus 10% tax is $110." },
    faq: [
      { q: "Which mode should I use for a receipt total?", a: "Use 'includes tax' if the amount you have already has tax baked in and you want to find the pre-tax price." },
      { q: "Does this handle multiple tax rates (e.g. state + local)?", a: "Combine them into a single effective rate first, then enter that total rate here." },
    ],
    related: ["discount-calculator", "salary-calculator"],
  },
  {
    slug: "salary-calculator",
    title: "Salary / Take-home Pay Calculator",
    category: "finance",
    description: "Estimate monthly take-home pay from a gross annual salary and effective tax rate.",
    fields: [
      { id: "grossAnnual", label: "Gross annual salary", type: "number", defaultValue: "60000", required: true },
      { id: "effectiveTaxRate", label: "Effective tax rate (%)", type: "number", defaultValue: "20", required: true },
      { id: "otherMonthlyDeductions", label: "Other monthly deductions (optional)", type: "number", defaultValue: "0" },
    ],
    calculate: calculateSalary,
    formula: "Monthly take-home = (Gross × (1 − Rate/100)) ÷ 12 − other deductions",
    explanation: "Take-home pay is what remains after taxes and other deductions (like retirement contributions or insurance premiums) are subtracted from gross pay, spread across 12 months.",
    example: { inputs: { grossAnnual: "60000", effectiveTaxRate: "20", otherMonthlyDeductions: "200" }, note: "A $60,000 salary at a 20% effective tax rate with $200/month in other deductions." },
    faq: [
      { q: "What is an 'effective' tax rate?", a: "It's your total tax paid divided by your total income — a blended rate across all tax brackets, unlike the marginal rate on your last dollar earned." },
      { q: "Does this include payroll taxes?", a: "Fold any payroll taxes into your effective tax rate, or list them under other monthly deductions." },
    ],
    related: ["tax-calculator", "inflation-calculator"],
  },
  {
    slug: "currency-converter",
    title: "Currency Conversion Calculator",
    category: "finance",
    description: "Convert between major world currencies using an illustrative static rate snapshot.",
    fields: [
      { id: "amount", label: "Amount", type: "number", defaultValue: "100", required: true },
      { id: "from", label: "From currency", type: "select", defaultValue: "USD", options: currencyOptions },
      { id: "to", label: "To currency", type: "select", defaultValue: "INR", options: currencyOptions },
    ],
    calculate: calculateCurrency,
    formula: "Result = (Amount ÷ Rate[from→USD]) × Rate[USD→to]",
    explanation: "Currency conversion routes every pair through USD as a common base. This deployment ships with a static illustrative rate snapshot — production use requires wiring in a live FX data provider (see the on-page notice).",
    example: { inputs: { amount: "100", from: "USD", to: "INR" }, note: "Rates shown are a dated snapshot for demonstration only." },
    faq: [
      { q: "Are these live exchange rates?", a: "No. This build uses a static, dated snapshot clearly labeled on the result. Do not use it for real transactions — connect a live FX API before relying on it financially." },
      { q: "Can more currencies be added?", a: "Yes — the currency registry (lib/calculations/finance.ts) is a flat lookup table; add any ISO 4217 code with its USD rate." },
    ],
    related: ["inflation-calculator", "tip-calculator"],
  },
  {
    slug: "inflation-calculator",
    title: "Inflation Calculator",
    category: "finance",
    description: "Project the future cost of goods under inflation, or find today's equivalent purchasing power.",
    fields: [
      { id: "presentValue", label: "Present value", type: "number", defaultValue: "1000", required: true },
      { id: "annualInflationRate", label: "Annual inflation rate (%)", type: "number", defaultValue: "6", required: true },
      { id: "years", label: "Years", type: "number", defaultValue: "10", required: true },
    ],
    calculate: calculateInflation,
    formula: "Future cost = Present value × (1 + rate/100)^years",
    explanation: "Inflation erodes purchasing power over time. This calculator projects what a given amount will cost in the future, and shows what today's amount will feel like in future purchasing terms.",
    example: { inputs: { presentValue: "1000", annualInflationRate: "6", years: "10" }, note: "$1,000 of goods today will cost about $1,791 in 10 years at 6% average inflation." },
    faq: [
      { q: "Is inflation constant every year in reality?", a: "No — this uses a constant average rate for simplicity; real inflation varies year to year." },
      { q: "How does this relate to compound interest?", a: "It uses the exact same compounding formula, just interpreted as rising prices instead of growing savings." },
    ],
    related: ["compound-interest-calculator", "salary-calculator"],
  },
  {
    slug: "tip-calculator",
    title: "Tip Calculator",
    category: "finance",
    description: "Calculate a tip and split the total bill evenly between any number of people.",
    fields: [
      { id: "billAmount", label: "Bill amount", type: "number", defaultValue: "80", required: true },
      { id: "tipPercent", label: "Tip percentage", type: "number", defaultValue: "18", required: true },
      { id: "splitBetween", label: "Split between (people)", type: "number", defaultValue: "1" },
    ],
    calculate: calculateTip,
    formula: "Per person = (Bill × (1 + Tip% ÷ 100)) ÷ People",
    explanation: "Tipping adds a percentage of the bill as a gratuity. When splitting a group bill, the tip and bill are combined first, then divided evenly across everyone at the table.",
    example: { inputs: { billAmount: "80", tipPercent: "18", splitBetween: "4" }, note: "An $80 bill with an 18% tip split 4 ways is $23.60 per person." },
    faq: [
      { q: "Should tip be calculated before or after tax?", a: "Conventions vary by region; this calculator applies the tip percentage to whatever amount you enter as the bill." },
      { q: "Does splitting round the total?", a: "The per-person amount is shown to the cent, so you may want to round up slightly in practice." },
    ],
    related: ["percentage-calculator", "discount-calculator"],
  },
];
