import { CalculatorDefinition } from "../lib/types";
import {
  calculateScientific, calculatePercentageChange, calculateExponent, calculateSquareRoot,
  calculateLogarithm, calculateGCD, calculateLCM, calculatePrime, calculateFactorial,
  calculateProbability, calculatePermCombo, calculateAlgebra, calculateQuadratic,
  calculateGeometry, calculatePythagorean,
} from "../lib/calculations/mathScience";

export const mathScienceCalculators: CalculatorDefinition[] = [
  {
    slug: "scientific-calculator",
    title: "Scientific Calculator",
    category: "math-science",
    description: "Evaluate expressions with trig, logs, roots, and constants — no eval(), a safe math parser only.",
    fields: [
      { id: "expression", label: "Expression", type: "text", placeholder: "sin(45 deg) + sqrt(16)", defaultValue: "sin(45 deg) + sqrt(16)", required: true },
    ],
    calculate: calculateScientific,
    formula: "Parsed and evaluated using a dedicated math expression parser (mathjs) — never JavaScript eval()",
    explanation: "This calculator understands standard mathematical notation — operators, functions like sin/cos/log/sqrt, and constants like π and e — through a parser built specifically for math, so it can never execute arbitrary code.",
    example: { inputs: { expression: "2 + 3 * 4" }, note: "2 + 3 × 4 = 14 (multiplication before addition)" },
    faq: [
      { q: "What functions are supported?", a: "Standard functions including sin, cos, tan, asin, acos, atan, log, ln, sqrt, exp, abs, floor, ceil, and factorial (as n!)." },
      { q: "Can I use degrees instead of radians?", a: 'Yes — append "deg" to an angle, e.g. sin(45 deg).' },
    ],
    related: ["algebra-calculator", "quadratic-equation-calculator"],
  },
  {
    slug: "percentage-change-calculator",
    title: "Percentage Change Calculator",
    category: "math-science",
    description: "Calculate the percentage increase or decrease between two values.",
    fields: [
      { id: "oldValue", label: "Original value", type: "number", defaultValue: "50", required: true },
      { id: "newValue", label: "New value", type: "number", defaultValue: "75", required: true },
    ],
    calculate: calculatePercentageChange,
    formula: "% change = ((New − Old) ÷ |Old|) × 100",
    explanation: "Percentage change measures how much a value has grown or shrunk relative to its starting point, expressed as a signed percentage.",
    example: { inputs: { oldValue: "50", newValue: "75" }, note: "Going from 50 to 75 is a +50% change." },
    faq: [
      { q: "What does a negative result mean?", a: "A negative percentage change means the new value is smaller than the original — a decrease." },
      { q: "Why use the absolute value of the old value?", a: "It keeps the sign of the result meaningful (increase vs. decrease) even when the original value itself is negative." },
    ],
    related: ["percentage-calculator", "roi-calculator"],
  },
  {
    slug: "exponent-calculator",
    title: "Exponent / Power Calculator",
    category: "math-science",
    description: "Raise any base to any exponent, including negative and fractional exponents.",
    fields: [
      { id: "base", label: "Base", type: "number", defaultValue: "2", required: true },
      { id: "exponent", label: "Exponent", type: "number", defaultValue: "10", required: true },
    ],
    calculate: calculateExponent,
    formula: "Result = base^exponent",
    explanation: "Exponentiation repeatedly multiplies the base by itself. Negative exponents produce reciprocals, and fractional exponents produce roots.",
    example: { inputs: { base: "2", exponent: "10" }, note: "2^10 = 1024" },
    faq: [
      { q: "What does a negative exponent mean?", a: "base^(−n) = 1 ÷ base^n — it produces the reciprocal of the positive-exponent result." },
      { q: "What about a fractional exponent?", a: "base^(1/n) is equivalent to the nth root of the base." },
    ],
    related: ["square-root-calculator", "scientific-calculator"],
  },
  {
    slug: "square-root-calculator",
    title: "Square Root Calculator",
    category: "math-science",
    description: "Find the square root or any nth root of a number.",
    fields: [
      { id: "value", label: "Value", type: "number", defaultValue: "144", required: true },
      { id: "degree", label: "Root degree (2 = square root, 3 = cube root, etc.)", type: "number", defaultValue: "2" },
    ],
    calculate: calculateSquareRoot,
    formula: "Result = value^(1/n)",
    explanation: "A square root finds the number that, multiplied by itself, gives the original value. This calculator generalizes to any root degree.",
    example: { inputs: { value: "144", degree: "2" }, note: "√144 = 12" },
    faq: [
      { q: "Can I take the square root of a negative number?", a: "Not with a real result — even roots of negative numbers are complex, so this calculator flags them as invalid." },
      { q: "Can I take the cube root of a negative number?", a: "Yes — odd roots of negative numbers are real, e.g. the cube root of −8 is −2." },
    ],
    related: ["exponent-calculator", "pythagorean-theorem-calculator"],
  },
  {
    slug: "logarithm-calculator",
    title: "Logarithm Calculator",
    category: "math-science",
    description: "Calculate logarithms in any base, including natural log (ln) and log base 10.",
    fields: [
      { id: "value", label: "Value", type: "number", defaultValue: "1000", required: true },
      { id: "base", label: "Base ('e' for natural log, or a number)", type: "text", defaultValue: "10", required: true },
    ],
    calculate: calculateLogarithm,
    formula: "log_base(value) = ln(value) ÷ ln(base)",
    explanation: "A logarithm answers 'to what power must the base be raised to get this value?' The natural logarithm uses base e ≈ 2.71828.",
    example: { inputs: { value: "1000", base: "10" }, note: "log₁₀(1000) = 3, since 10³ = 1000" },
    faq: [
      { q: "How do I compute a natural log?", a: 'Enter "e" as the base.' },
      { q: "Why must the value be positive?", a: "Logarithms of zero or negative numbers are undefined in the real numbers." },
    ],
    related: ["exponent-calculator", "scientific-calculator"],
  },
  {
    slug: "gcd-calculator",
    title: "GCD Calculator",
    category: "math-science",
    description: "Find the greatest common divisor of two or more whole numbers.",
    fields: [
      { id: "numbers", label: "Numbers (comma or space separated)", type: "text", defaultValue: "48, 60, 18", required: true },
    ],
    calculate: calculateGCD,
    formula: "GCD found via the Euclidean algorithm, applied pairwise across all numbers",
    explanation: "The greatest common divisor is the largest whole number that divides every input number evenly. It's the basis for simplifying fractions and ratios.",
    example: { inputs: { numbers: "48, 60, 18" }, note: "GCD(48, 60, 18) = 6" },
    faq: [
      { q: "What if one of the numbers is 0?", a: "GCD(0, n) = n for any non-zero n, since every number divides 0." },
      { q: "How is GCD used in simplifying fractions?", a: "Dividing both numerator and denominator by their GCD reduces a fraction to its lowest terms." },
    ],
    related: ["lcm-calculator", "fraction-calculator"],
  },
  {
    slug: "lcm-calculator",
    title: "LCM Calculator",
    category: "math-science",
    description: "Find the least common multiple of two or more whole numbers.",
    fields: [
      { id: "numbers", label: "Numbers (comma or space separated)", type: "text", defaultValue: "4, 6", required: true },
    ],
    calculate: calculateLCM,
    formula: "LCM(a,b) = |a×b| ÷ GCD(a,b), applied pairwise",
    explanation: "The least common multiple is the smallest positive number that all input numbers divide into evenly — commonly used to find a common denominator when adding fractions.",
    example: { inputs: { numbers: "4, 6" }, note: "LCM(4, 6) = 12" },
    faq: [
      { q: "Can LCM be found for more than two numbers?", a: "Yes — the calculator computes it pairwise across the whole list." },
      { q: "Why is LCM undefined for zero?", a: "Since zero has no positive multiples other than zero itself, an LCM involving zero is undefined in the usual sense." },
    ],
    related: ["gcd-calculator", "fraction-calculator"],
  },
  {
    slug: "prime-number-calculator",
    title: "Prime Number Calculator",
    category: "math-science",
    description: "Check whether a number is prime and see its full prime factorization.",
    fields: [
      { id: "value", label: "Number", type: "number", defaultValue: "17", required: true },
    ],
    calculate: calculatePrime,
    formula: "Trial division up to √n; a number is prime if no factor divides it evenly besides 1 and itself",
    explanation: "A prime number has exactly two positive divisors: 1 and itself. This calculator tests primality by trial division and shows the full factorization either way.",
    example: { inputs: { value: "17" }, note: "17 is prime." },
    faq: [
      { q: "Is 1 a prime number?", a: "No — by definition, prime numbers must be greater than 1." },
      { q: "Why only check divisors up to √n?", a: "If n has a factor larger than √n, it must also have a corresponding factor smaller than √n, so checking beyond that point is redundant." },
    ],
    related: ["gcd-calculator", "factorial-calculator"],
  },
  {
    slug: "factorial-calculator",
    title: "Factorial Calculator",
    category: "math-science",
    description: "Calculate n! — the product of all positive integers up to n.",
    fields: [
      { id: "value", label: "n", type: "number", defaultValue: "5", required: true },
    ],
    calculate: calculateFactorial,
    formula: "n! = n × (n−1) × (n−2) × ... × 1,  with 0! = 1",
    explanation: "Factorial counts the number of ways to arrange n distinct items in order. It grows extremely fast, which is why very large inputs overflow standard number precision.",
    example: { inputs: { value: "5" }, note: "5! = 5×4×3×2×1 = 120" },
    faq: [
      { q: "Why is 0! equal to 1?", a: "By convention (and to keep combinatorial formulas consistent), the empty product is defined as 1." },
      { q: "Why is there an upper limit on n?", a: "Factorials larger than 170! exceed the range that can be represented precisely as a standard floating-point number." },
    ],
    related: ["permutation-combination-calculator", "probability-calculator"],
  },
  {
    slug: "probability-calculator",
    title: "Probability Calculator",
    category: "math-science",
    description: "Calculate the probability of an event given favorable and total outcomes.",
    fields: [
      { id: "favorableOutcomes", label: "Favorable outcomes", type: "number", defaultValue: "1", required: true },
      { id: "totalOutcomes", label: "Total possible outcomes", type: "number", defaultValue: "6", required: true },
    ],
    calculate: calculateProbability,
    formula: "P(event) = Favorable outcomes ÷ Total outcomes",
    explanation: "Basic probability assumes all outcomes are equally likely, and measures the chance of a specific event as a fraction of all possible outcomes.",
    example: { inputs: { favorableOutcomes: "1", totalOutcomes: "6" }, note: "Rolling a specific number on a fair six-sided die: 1/6 ≈ 16.67%." },
    faq: [
      { q: "Can probability be greater than 1?", a: "No — a valid probability is always between 0 and 1 (0% to 100%), so favorable outcomes can never exceed total outcomes." },
      { q: "Does this handle combined/conditional probability?", a: "This calculator covers simple single-event probability; combine multiple results manually for compound events." },
    ],
    related: ["permutation-combination-calculator", "factorial-calculator"],
  },
  {
    slug: "permutation-combination-calculator",
    title: "Permutation & Combination Calculator",
    category: "math-science",
    description: "Calculate the number of permutations P(n,r) or combinations C(n,r).",
    fields: [
      { id: "n", label: "n (total items)", type: "number", defaultValue: "5", required: true },
      { id: "r", label: "r (items chosen)", type: "number", defaultValue: "2", required: true },
      { id: "mode", label: "Type", type: "select", defaultValue: "permutation", options: [
        { label: "Permutation (order matters)", value: "permutation" },
        { label: "Combination (order doesn't matter)", value: "combination" },
      ] },
    ],
    calculate: calculatePermCombo,
    formula: "P(n,r) = n! ÷ (n−r)!     |     C(n,r) = n! ÷ (r!(n−r)!)",
    explanation: "Permutations count ordered arrangements; combinations count selections where order doesn't matter. Combinations are always smaller or equal to permutations for the same n and r.",
    example: { inputs: { n: "5", r: "2", mode: "permutation" }, note: "P(5,2) = 20 ordered pairs from 5 items." },
    faq: [
      { q: "When should I use combinations instead of permutations?", a: "Use combinations when the selection order doesn't matter — like choosing a committee — and permutations when order does matter, like assigning 1st/2nd/3rd place." },
      { q: "What if r equals n?", a: "P(n,n) = n! and C(n,n) = 1 — there's only one way to select every item, but n! ways to order them all." },
    ],
    related: ["factorial-calculator", "probability-calculator"],
  },
  {
    slug: "algebra-calculator",
    title: "Algebra Calculator",
    category: "math-science",
    description: "Solve linear equations of the form a·x + b = c for x.",
    fields: [
      { id: "a", label: "a", type: "number", defaultValue: "2", required: true },
      { id: "b", label: "b", type: "number", defaultValue: "3", required: true },
      { id: "c", label: "c", type: "number", defaultValue: "11", required: true },
    ],
    calculate: calculateAlgebra,
    formula: "x = (c − b) ÷ a",
    explanation: "A linear equation has one variable raised to the first power. Isolating x by moving b to the other side and dividing by a gives the unique solution (when a ≠ 0).",
    example: { inputs: { a: "2", b: "3", c: "11" }, note: "2x + 3 = 11  →  x = 4" },
    faq: [
      { q: "What happens if a = 0?", a: "If a = 0 and b = c, every x is a solution; if b ≠ c, there is no solution — both cases are flagged explicitly." },
      { q: "Can this solve quadratic equations?", a: "No — use the dedicated Quadratic Equation Calculator for ax² + bx + c = 0." },
    ],
    related: ["quadratic-equation-calculator", "scientific-calculator"],
  },
  {
    slug: "quadratic-equation-calculator",
    title: "Quadratic Equation Calculator",
    category: "math-science",
    description: "Solve ax² + bx + c = 0 using the quadratic formula, including complex roots.",
    fields: [
      { id: "a", label: "a", type: "number", defaultValue: "1", required: true },
      { id: "b", label: "b", type: "number", defaultValue: "-5", required: true },
      { id: "c", label: "c", type: "number", defaultValue: "6", required: true },
    ],
    calculate: calculateQuadratic,
    formula: "x = (−b ± √(b² − 4ac)) ÷ 2a",
    explanation: "The discriminant (b² − 4ac) determines the nature of the roots: two real roots when positive, one repeated real root when zero, and two complex roots when negative.",
    example: { inputs: { a: "1", b: "-5", c: "6" }, note: "x² − 5x + 6 = 0  →  x = 2 or x = 3" },
    faq: [
      { q: "What does a negative discriminant mean?", a: "The equation has no real solutions — its two roots are complex conjugates." },
      { q: "Can 'a' be zero?", a: "No — with a = 0 the equation is linear, not quadratic. Use the Algebra Calculator instead." },
    ],
    related: ["algebra-calculator", "square-root-calculator"],
  },
  {
    slug: "geometry-calculator",
    title: "Geometry Calculator",
    category: "math-science",
    description: "Calculate volume and surface area for 3D solids: spheres, cylinders, and cones.",
    fields: [
      { id: "shape", label: "Shape", type: "select", defaultValue: "sphere", options: [
        { label: "Sphere", value: "sphere" }, { label: "Cylinder", value: "cylinder" }, { label: "Cone", value: "cone" },
      ] },
      { id: "radius", label: "Radius", type: "number", defaultValue: "7", required: true },
      { id: "height", label: "Height (cylinder/cone)", type: "number", defaultValue: "10" },
    ],
    calculate: calculateGeometry,
    formula: "Sphere: V = (4/3)πr³, S = 4πr²   |   Cylinder: V = πr²h, S = 2πr(r+h)   |   Cone: V = (1/3)πr²h, S = πr(r+slant)",
    explanation: "Three-dimensional solids have both a volume (the space they occupy) and a surface area (the area of their outer boundary). Each shape follows its own derived formula.",
    example: { inputs: { shape: "sphere", radius: "7" }, note: "A sphere of radius 7 has a volume of about 1436.76 and surface area of about 615.75." },
    faq: [
      { q: "What's the slant height of a cone?", a: "It's the distance from the base edge to the apex along the cone's surface, computed as √(r² + h²)." },
      { q: "Does this cover cubes or pyramids?", a: "This build covers sphere, cylinder, and cone; the registry can be extended with additional 3D shapes without touching the page template." },
    ],
    related: ["area-perimeter-calculator", "pythagorean-theorem-calculator"],
  },
  {
    slug: "area-perimeter-calculator",
    title: "Area & Perimeter Calculator",
    category: "math-science",
    description: "Calculate area and perimeter for 2D shapes: circles, rectangles, and triangles.",
    fields: [
      { id: "shape", label: "Shape", type: "select", defaultValue: "circle", options: [
        { label: "Circle", value: "circle" }, { label: "Rectangle", value: "rectangle" }, { label: "Triangle", value: "triangle" },
      ] },
      { id: "radius", label: "Radius (circle)", type: "number", defaultValue: "7" },
      { id: "width", label: "Width (rectangle)", type: "number" },
      { id: "height", label: "Height (rectangle/triangle)", type: "number" },
      { id: "base", label: "Base (triangle)", type: "number" },
      { id: "side1", label: "Side 1 (triangle, alternative to base/height)", type: "number" },
      { id: "side2", label: "Side 2 (triangle)", type: "number" },
      { id: "side3", label: "Side 3 (triangle)", type: "number" },
    ],
    calculate: calculateGeometry,
    formula: "Circle: A = πr², C = 2πr   |   Rectangle: A = w×h, P = 2(w+h)   |   Triangle (Heron's): A = √(s(s−a)(s−b)(s−c))",
    explanation: "Area measures the space enclosed by a 2D shape; perimeter (or circumference for circles) measures the distance around its boundary. For triangles, either base & height or all three side lengths can be used.",
    example: { inputs: { shape: "circle", radius: "7" }, note: "A circle of radius 7 has an area of about 153.94 and circumference of about 43.98." },
    faq: [
      { q: "Which triangle inputs should I use?", a: "Provide either base & height, or all three side lengths — not a mix." },
      { q: "Why does the calculator reject some triangle side lengths?", a: "Three lengths only form a valid triangle if each side is shorter than the sum of the other two (the triangle inequality)." },
    ],
    related: ["geometry-calculator", "pythagorean-theorem-calculator"],
  },
  {
    slug: "pythagorean-theorem-calculator",
    title: "Pythagorean Theorem Calculator",
    category: "math-science",
    description: "Find a missing side of a right triangle given the other two sides.",
    fields: [
      { id: "a", label: "Side a", type: "number", defaultValue: "3" },
      { id: "b", label: "Side b", type: "number", defaultValue: "4" },
      { id: "c", label: "Hypotenuse c (leave blank if unknown)", type: "number" },
    ],
    calculate: calculatePythagorean,
    formula: "a² + b² = c²",
    explanation: "In a right triangle, the square of the hypotenuse equals the sum of squares of the other two sides. Enter any two sides and leave the unknown one blank.",
    example: { inputs: { a: "3", b: "4" }, note: "3² + 4² = 5² → hypotenuse = 5" },
    faq: [
      { q: "Which side is the hypotenuse?", a: "The hypotenuse is always the longest side, opposite the right angle — enter it as 'c'." },
      { q: "What if I enter all three sides?", a: "Leave exactly one of the three fields blank; the calculator solves for whichever one is missing." },
    ],
    related: ["geometry-area-perimeter-calculator", "square-root-calculator"],
  },
];
